#!/bin/bash

docker build . -t catchpole
docker run -e "DB_CONN_STRING=$DB_CONN_STRING" -e "FIREBASE_ADMIN_CREDS=$FIREBASE_ADMIN_CREDS" -e "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" -e "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" -e "CATCHPOLE_ADMIN_PASSWORD=$CATCHPOLE_ADMIN_PASSWORD" -e "STRIPE_PRICE_ID=$STRIPE_PRICE_ID" -e "DB_MAX_IDLE_CONNS=$DB_MAX_IDLE_CONNS" -e "DB_MAX_OPEN_CONNS=$DB_MAX_OPEN_CONNS" -e "STAGE=prod" -p 5000:5000 catchpole
